"""Tests for app.routers.rag — POST /find endpoint (Find mode).

Spec: ``docs/superpowers/specs/2026-04-30-intelligence-find-mode.md`` §3.2.

Find mode is the file-listing sibling of Ask mode. It reuses Stage A-D
(decompose / history filter / category expansion / scoped retrieval)
but skips Stage E (LLM answer generation) entirely. The router returns
single-shot JSON, NOT SSE — there is no LLM token stream to multiplex.

These tests exercise the router-level concerns:

* Drive header gating: ``X-Lit-Drive`` is required, mirroring /ask.
* Feature gating: ``features.rag=False`` and ``LLM disabled`` both
  reject the request as 4xx (the same gating as /ask, since Find
  shares the LLM-driven Stages A + C).
* Body ``overrides`` (chip-edited query) take precedence over the
  LLM-decomposed query.
* ``viewer_id`` graceful fallback: if the request asks for personal
  scope but no ``X-Lit-Viewer-Id`` header is present, the endpoint
  must NOT 4xx — instead Stage B is silently skipped.
* Response shape from spec §3.2: ``decomposed``, ``results``, ``total``,
  ``limit``, with hit text populated from the retrieve segment (NOT
  generated by an LLM).
* Empty results return 200 with an empty array, NOT 404.

All tests RED until Phase 4 (the new ``/find`` endpoint, ``FindRequest``
/ ``FindResponse`` schemas, and the ``find_files`` service function)
land. The import surface itself is the gate — if any of the new symbols
is missing, the module fails to import and pytest reports the failure
as a collection error which is the strongest possible RED signal.
"""

from __future__ import annotations

import sys
from unittest.mock import AsyncMock, MagicMock

import pytest
from fastapi import HTTPException

# Heavy ML deps are stubbed before importing app.routers.rag, since
# importing the router transitively pulls in app.search and friends.
for _mod in (
    "PIL",
    "PIL.Image",
    "open_clip",
    "torch",
    "sentence_transformers",
    "faster_whisper",
    "onnxruntime",
    "transformers",
    "janome",
    "janome.tokenizer",
    "sqlite_vec",
):
    if _mod not in sys.modules:
        sys.modules[_mod] = MagicMock()

from app.config import LLMConfig, RagConfig  # noqa: E402

# These imports are part of the RED gate. They will fail until Phase 4
# ships the new router endpoint and schema models. Tests below depend
# on them.
from app.routers.rag import find_endpoint  # noqa: E402  # NEW symbol
from app.schemas import FindRequest  # noqa: E402  # NEW symbol


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture()
def find_enabled(monkeypatch, make_settings):
    """Settings with features.rag=True and LLM enabled.

    Find mode reuses the same gating as /ask: features.rag toggles the
    whole RAG stack (decompose + retrieve + expand), and the LLM client
    must be enabled for Stages A and C.
    """
    settings = make_settings(
        features=type(make_settings().features)(rag=True),
        llm=LLMConfig(
            provider="openai_compatible",
            base_url="http://localhost:11434/v1",
            model="llama3",
        ),
        rag=RagConfig(),
    )
    monkeypatch.setattr("app.config.settings", settings)
    monkeypatch.setattr("app.routers.rag.settings", settings)

    llm_stub = MagicMock()
    llm_stub.enabled = True
    monkeypatch.setattr(
        "app.routers.rag.get_llm_client", lambda: llm_stub
    )
    return settings


@pytest.fixture()
def find_rag_disabled(monkeypatch, make_settings):
    """features.rag=False — Find mode should reject as 4xx."""
    settings = make_settings(
        features=type(make_settings().features)(rag=False),
        llm=LLMConfig(
            provider="openai_compatible",
            base_url="http://localhost:11434/v1",
            model="llama3",
        ),
    )
    monkeypatch.setattr("app.config.settings", settings)
    monkeypatch.setattr("app.routers.rag.settings", settings)

    llm_stub = MagicMock()
    llm_stub.enabled = True
    monkeypatch.setattr(
        "app.routers.rag.get_llm_client", lambda: llm_stub
    )
    return settings


@pytest.fixture()
def find_llm_disabled(monkeypatch, make_settings):
    """LLM provider=disabled — Find mode should reject as 4xx."""
    settings = make_settings(
        features=type(make_settings().features)(rag=True),
        llm=LLMConfig(provider="disabled"),
    )
    monkeypatch.setattr("app.config.settings", settings)
    monkeypatch.setattr("app.routers.rag.settings", settings)

    llm_stub = MagicMock()
    llm_stub.enabled = False
    monkeypatch.setattr(
        "app.routers.rag.get_llm_client", lambda: llm_stub
    )
    return settings


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _stub_find_response(
    *,
    results: list[dict] | None = None,
    decomposed: dict | None = None,
    total: int | None = None,
    limit: int = 20,
):
    """Build a plausible FindResponse-like object for service stubs.

    The router test layer doesn't care about the precise dataclass /
    pydantic model used internally by the service — we just need
    ``find_files`` to return *something* the router can serialise. A
    plain dict is the lowest-friction shape; we wrap it in MagicMock
    only for tests that need to spy on attribute access.
    """
    payload = {
        "decomposed": decomposed
        or {
            "time_range": {
                "kind": "none",
                "value": "none",
                "after": None,
                "before": None,
            },
            "personal_scope": "none",
            "file_type_hint": "none",
            "semantic_query": "",
            "category_expansion": [],
        },
        "results": results if results is not None else [],
        "total": total if total is not None else (len(results) if results else 0),
        "limit": limit,
    }
    return payload


def _result_item(
    *,
    file_id: str = "f-abc123",
    score: float = 0.82,
    hit_kind: str = "transcript",
    hit_text: str = "...宇宙船が時空を超えて...",
    name: str = "Interstellar.mp4",
    file_type: str = "video",
) -> dict:
    return {
        "file_id": file_id,
        "score": score,
        "hit": {
            "kind": hit_kind,
            "location": {"start_seconds": 415.2, "end_seconds": 460.0},
            "text": hit_text,
        },
        "file": {
            "name": name,
            "file_type": file_type,
            "thumbnail_url": f"/api/files/{file_id}/thumbnail",
            "viewed_at": "2026-04-27T19:30:00Z",
        },
    }


# ---------------------------------------------------------------------------
# Gating: drive header / feature flag / LLM
# ---------------------------------------------------------------------------


class TestFindEndpointGating:
    """Find mode shares /ask's gating layers."""

    @pytest.mark.asyncio
    async def test_returns_400_when_drive_header_missing(self, find_enabled):
        """No X-Lit-Drive header -> 400 from require_drive dependency."""
        # The dependency raises 400 when called with an empty header.
        # We invoke the handler directly with drive="" to mimic the
        # behaviour the dependency would produce on a missing header.
        body = FindRequest(question="先週観た映画でSF")

        with pytest.raises(HTTPException) as exc_info:
            await find_endpoint(
                body=body,
                access_token="tok",
                drive="",  # simulates header-missing rejection
                viewer_id=None,
            )

        assert exc_info.value.status_code == 400

    @pytest.mark.asyncio
    async def test_returns_400_when_rag_disabled(self, find_rag_disabled):
        body = FindRequest(question="a valid question")

        with pytest.raises(HTTPException) as exc_info:
            await find_endpoint(
                body=body,
                access_token="tok",
                drive="movies",
                viewer_id=None,
            )

        assert exc_info.value.status_code == 400

    @pytest.mark.asyncio
    async def test_returns_400_when_llm_disabled(self, find_llm_disabled):
        body = FindRequest(question="a valid question")

        with pytest.raises(HTTPException) as exc_info:
            await find_endpoint(
                body=body,
                access_token="tok",
                drive="movies",
                viewer_id=None,
            )

        assert exc_info.value.status_code == 400

    @pytest.mark.asyncio
    async def test_returns_400_for_short_question(self, find_enabled):
        """Mirror /ask: <3 chars after strip is rejected before service call."""
        body = FindRequest(question="ab")

        with pytest.raises(HTTPException) as exc_info:
            await find_endpoint(
                body=body,
                access_token="tok",
                drive="movies",
                viewer_id=None,
            )

        assert exc_info.value.status_code == 400


# ---------------------------------------------------------------------------
# Happy path: response shape from spec §3.2
# ---------------------------------------------------------------------------


class TestFindEndpointResponseShape:
    @pytest.mark.asyncio
    async def test_returns_200_with_full_response_shape(
        self, find_enabled, monkeypatch
    ):
        """Spec §3.2 requires decomposed + results + total + limit."""
        decomposed = {
            "time_range": {
                "kind": "relative",
                "value": "last_week",
                "after": "2026-04-23T00:00:00Z",
                "before": "2026-04-30T00:00:00Z",
            },
            "personal_scope": "viewed",
            "file_type_hint": "video",
            "semantic_query": "SF",
            "category_expansion": [
                "science fiction",
                "宇宙船",
                "ロボット",
                "ディストピア",
            ],
        }
        items = [_result_item(file_id="f-abc123"), _result_item(file_id="f-def456")]

        monkeypatch.setattr(
            "app.routers.rag.find_files",
            AsyncMock(
                return_value=_stub_find_response(
                    results=items, decomposed=decomposed, total=8, limit=20
                )
            ),
        )

        body = FindRequest(question="先週観た映画の中で SF っぽいのどれ？")
        result = await find_endpoint(
            body=body,
            access_token="tok",
            drive="movies",
            viewer_id="x" * 16,
        )

        # The result is the JSON body or a dict-shaped pydantic model.
        # Either way, the spec keys must be present.
        payload = result if isinstance(result, dict) else result.model_dump()
        assert set(payload.keys()) >= {
            "decomposed",
            "results",
            "total",
            "limit",
        }
        assert payload["decomposed"]["time_range"]["value"] == "last_week"
        assert payload["decomposed"]["personal_scope"] == "viewed"
        assert payload["decomposed"]["file_type_hint"] == "video"
        assert payload["decomposed"]["semantic_query"] == "SF"
        assert payload["decomposed"]["category_expansion"] == [
            "science fiction",
            "宇宙船",
            "ロボット",
            "ディストピア",
        ]
        assert payload["limit"] == 20
        assert payload["total"] == 8
        assert len(payload["results"]) == 2

    @pytest.mark.asyncio
    async def test_response_decomposed_has_required_keys(
        self, find_enabled, monkeypatch
    ):
        """``decomposed`` block must include all five spec-mandated keys.

        Even when the LLM emits "no signal" the keys MUST be present so
        the frontend can render its chip layout without conditional
        existence checks.
        """
        empty_decomposed = {
            "time_range": {
                "kind": "none",
                "value": "none",
                "after": None,
                "before": None,
            },
            "personal_scope": "none",
            "file_type_hint": "none",
            "semantic_query": "",
            "category_expansion": [],
        }
        monkeypatch.setattr(
            "app.routers.rag.find_files",
            AsyncMock(
                return_value=_stub_find_response(
                    results=[], decomposed=empty_decomposed, total=0
                )
            ),
        )

        body = FindRequest(question="anything goes here")
        result = await find_endpoint(
            body=body,
            access_token=None,
            drive="movies",
            viewer_id=None,
        )

        payload = result if isinstance(result, dict) else result.model_dump()
        for key in (
            "time_range",
            "personal_scope",
            "file_type_hint",
            "semantic_query",
            "category_expansion",
        ):
            assert key in payload["decomposed"], (
                f"decomposed missing required spec key: {key}"
            )

    @pytest.mark.asyncio
    async def test_empty_results_returns_200_not_404(
        self, find_enabled, monkeypatch
    ):
        """Zero hits is a normal outcome, not an error."""
        monkeypatch.setattr(
            "app.routers.rag.find_files",
            AsyncMock(return_value=_stub_find_response(results=[], total=0)),
        )

        body = FindRequest(question="something with no matches at all")
        result = await find_endpoint(
            body=body,
            access_token="tok",
            drive="movies",
            viewer_id=None,
        )
        # If the endpoint mistakenly raised 404 we wouldn't reach here.
        payload = result if isinstance(result, dict) else result.model_dump()
        assert payload["results"] == []
        assert payload["total"] == 0

    @pytest.mark.asyncio
    async def test_hit_text_comes_from_retrieve_segment_not_llm(
        self, find_enabled, monkeypatch
    ):
        """Spec §3.3: Stage E_find calls the LLM ZERO times.

        The `hit.text` field must be populated from the retrieved
        segment text directly (tier 1 = primary source per hako
        ``SKiYgE6GtttlQW7fEwAY6``). LLM-generated reasoning text would
        violate the no-hallucination guarantee that motivates Find mode
        over Ask mode.
        """
        retrieve_text = "...this is the verbatim retrieved segment..."
        monkeypatch.setattr(
            "app.routers.rag.find_files",
            AsyncMock(
                return_value=_stub_find_response(
                    results=[_result_item(hit_text=retrieve_text)]
                )
            ),
        )

        body = FindRequest(question="what is this about")
        result = await find_endpoint(
            body=body,
            access_token="tok",
            drive="movies",
            viewer_id=None,
        )

        payload = result if isinstance(result, dict) else result.model_dump()
        assert payload["results"][0]["hit"]["text"] == retrieve_text


# ---------------------------------------------------------------------------
# Overrides (chip-edited query) precedence
# ---------------------------------------------------------------------------


class TestFindEndpointOverrides:
    """Body ``overrides`` are chip-edit reposts.

    When the user clicks the × on a chip the frontend rebuilds the
    structured query and re-POSTs with ``overrides`` populated. The
    router must forward ``overrides`` to the service, which uses it
    INSTEAD OF re-running query_decomposer.
    """

    @pytest.mark.asyncio
    async def test_overrides_are_forwarded_to_service(
        self, find_enabled, monkeypatch
    ):
        captured: dict = {}

        async def _capture(**kwargs):
            captured.update(kwargs)
            return _stub_find_response()

        monkeypatch.setattr("app.routers.rag.find_files", _capture)

        overrides = {
            "time_range": "none",  # chip × on time
            "personal_scope": "viewed",
            "file_type_hint": "video",
            "semantic_query": "SF",
        }
        body = FindRequest(
            question="先週観た映画でSF",
            overrides=overrides,
        )

        await find_endpoint(
            body=body,
            access_token="tok",
            drive="movies",
            viewer_id="x" * 16,
        )

        assert captured.get("overrides") == overrides

    @pytest.mark.asyncio
    async def test_overrides_omitted_when_not_provided(
        self, find_enabled, monkeypatch
    ):
        """Default chip-less request -> overrides is None / absent.

        The service can then run query_decomposer on its own.
        """
        captured: dict = {}

        async def _capture(**kwargs):
            captured.update(kwargs)
            return _stub_find_response()

        monkeypatch.setattr("app.routers.rag.find_files", _capture)

        body = FindRequest(question="先週観た映画でSF")
        await find_endpoint(
            body=body,
            access_token="tok",
            drive="movies",
            viewer_id="x" * 16,
        )

        # overrides is None by default — the service interprets that as
        # "decompose from scratch".
        assert captured.get("overrides") in (None, {})


# ---------------------------------------------------------------------------
# Viewer-id graceful fallback
# ---------------------------------------------------------------------------


class TestFindEndpointViewerFallback:
    """When the question implies personal scope but no viewer-id header
    is present, the endpoint must degrade gracefully — NOT 4xx."""

    @pytest.mark.asyncio
    async def test_personal_scope_request_without_viewer_id_succeeds(
        self, find_enabled, monkeypatch
    ):
        """No X-Lit-Viewer-Id header -> service runs without history filter.

        The router does NOT pre-validate that personal_scope queries
        have a viewer_id; that's the service's responsibility to handle
        gracefully (mirror /ask behaviour, which forwards None).
        """
        captured: dict = {}

        async def _capture(**kwargs):
            captured.update(kwargs)
            return _stub_find_response()

        monkeypatch.setattr("app.routers.rag.find_files", _capture)

        body = FindRequest(
            question="先週観た映画でSF",  # personal scope hint in NL
        )
        # Note: viewer_id=None despite the personal-scope question.
        result = await find_endpoint(
            body=body,
            access_token="tok",
            drive="movies",
            viewer_id=None,
        )

        # No exception, response returned, viewer_id forwarded as None.
        assert result is not None
        assert captured.get("viewer_id") is None

    @pytest.mark.asyncio
    async def test_viewer_id_forwarded_when_present(
        self, find_enabled, monkeypatch
    ):
        captured: dict = {}

        async def _capture(**kwargs):
            captured.update(kwargs)
            return _stub_find_response()

        monkeypatch.setattr("app.routers.rag.find_files", _capture)

        body = FindRequest(question="先週観た映画でSF")
        await find_endpoint(
            body=body,
            access_token="tok",
            drive="movies",
            viewer_id="abc123def456ghij",
        )

        assert captured.get("viewer_id") == "abc123def456ghij"


# ---------------------------------------------------------------------------
# Drive forwarding
# ---------------------------------------------------------------------------


class TestFindEndpointDriveForwarding:
    @pytest.mark.asyncio
    async def test_drive_forwarded_to_service(
        self, find_enabled, monkeypatch
    ):
        captured: dict = {}

        async def _capture(**kwargs):
            captured.update(kwargs)
            return _stub_find_response()

        monkeypatch.setattr("app.routers.rag.find_files", _capture)

        body = FindRequest(question="a valid question")
        await find_endpoint(
            body=body,
            access_token="tok",
            drive="MyMovies",
            viewer_id=None,
        )

        assert captured.get("drive") == "MyMovies"


# ---------------------------------------------------------------------------
# Limit handling
# ---------------------------------------------------------------------------


class TestFindEndpointLimit:
    @pytest.mark.asyncio
    async def test_default_limit_is_used_when_not_supplied(
        self, find_enabled, monkeypatch
    ):
        """Spec example uses limit=20."""
        captured: dict = {}

        async def _capture(**kwargs):
            captured.update(kwargs)
            return _stub_find_response()

        monkeypatch.setattr("app.routers.rag.find_files", _capture)

        body = FindRequest(question="a valid question")
        await find_endpoint(
            body=body,
            access_token="tok",
            drive="movies",
            viewer_id=None,
        )

        # Either body.limit defaults to 20 (pydantic default) and is
        # forwarded, or the router supplies it. Either way the service
        # must receive a positive int.
        forwarded_limit = captured.get("limit")
        assert isinstance(forwarded_limit, int) and forwarded_limit > 0

    @pytest.mark.asyncio
    async def test_explicit_limit_is_forwarded(
        self, find_enabled, monkeypatch
    ):
        captured: dict = {}

        async def _capture(**kwargs):
            captured.update(kwargs)
            return _stub_find_response(limit=5)

        monkeypatch.setattr("app.routers.rag.find_files", _capture)

        body = FindRequest(question="a valid question", limit=5)
        await find_endpoint(
            body=body,
            access_token="tok",
            drive="movies",
            viewer_id=None,
        )

        assert captured.get("limit") == 5


# ---------------------------------------------------------------------------
# FindRequest schema (defensive — guards the new pydantic model contract)
# ---------------------------------------------------------------------------


class TestFindRequestSchema:
    def test_minimum_question_required(self):
        with pytest.raises(Exception):
            FindRequest()  # type: ignore[call-arg]

    def test_empty_question_rejected(self):
        with pytest.raises(Exception):
            FindRequest(question="")

    def test_question_max_length_enforced(self):
        # Mirror AskRequest's 1000-char ceiling so giant queries can't
        # DoS the LLM behind the decomposer.
        with pytest.raises(Exception):
            FindRequest(question="x" * 1001)

    def test_overrides_optional(self):
        body = FindRequest(question="hello world question")
        assert getattr(body, "overrides", None) in (None, {})

    def test_overrides_accepted_when_dict(self):
        body = FindRequest(
            question="hello world question",
            overrides={
                "time_range": "none",
                "personal_scope": "viewed",
                "file_type_hint": "video",
                "semantic_query": "SF",
            },
        )
        assert body.overrides["personal_scope"] == "viewed"

    def test_limit_within_reasonable_bounds(self):
        # The service caps at 20 results per spec §3.2; reject silly
        # client values defensively.
        body = FindRequest(question="valid question text", limit=20)
        assert body.limit == 20
        with pytest.raises(Exception):
            FindRequest(question="valid question text", limit=0)
