"""What each prompt builder decides, and the two prompts a shared include reaches.

Assertions name the decision a builder makes — a field suppressed, a section
added, a language line chosen — rather than the whole rendered text, so
rewording a template does not force a regeneration that a logic regression
can ride along in.

``summaries/_common_rules.jinja2`` is the exception. Two system prompts
include it, so an edit there changes both without naming either. That file
keeps a byte-identical golden, regenerated by ``golden_prompts/_baseline.py``,
and both prompts are checked for carrying it.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from jinja2 import UndefinedError

from app.prompt_loader import render


GOLDEN_DIR = Path(__file__).resolve().parent / "golden_prompts"


def _golden(name: str) -> str:
    return (GOLDEN_DIR / name).read_bytes().decode("utf-8")


# ---------------------------------------------------------------------------
# Loader
# ---------------------------------------------------------------------------


def test_render_returns_string() -> None:
    out = render("auto_tags/system.jinja2", language_instruction="")
    assert isinstance(out, str)
    assert "tagging assistant" in out


def test_render_strict_undefined_raises_on_missing_var() -> None:
    with pytest.raises(UndefinedError):
        # auto_tags/system.jinja2 expects ``language_instruction``.
        render("auto_tags/system.jinja2")


@pytest.fixture
def _set_lang(monkeypatch):
    """Helper to flip ``settings.llm.output_language`` for one test."""

    def _apply(lang: str) -> None:
        from app.config import settings as real_settings

        # Settings dataclasses are frozen; bypass via object.__setattr__.
        object.__setattr__(real_settings.llm, "output_language", lang)

    return _apply


# ---------------------------------------------------------------------------
# Summaries — the include two system prompts share
# ---------------------------------------------------------------------------


def test_common_rules_matches_golden() -> None:
    """The one include with two consumers, so an edit reaches both."""
    assert render("summaries/_common_rules.jinja2") == _golden(
        "summaries_common_rules.txt"
    )


def test_both_summary_system_prompts_carry_the_shared_rules(_set_lang) -> None:
    from app.workers import summaries

    _set_lang("auto")
    shared = render("summaries/_common_rules.jinja2").strip()
    assert shared
    assert shared in summaries._build_system_prompt()
    assert shared in summaries._build_detailed_system_prompt()


@pytest.mark.parametrize(
    "build",
    ["_build_system_prompt", "_build_detailed_system_prompt"],
)
class TestSummariesSystemPrompt:
    @staticmethod
    def _out(build: str) -> str:
        from app.workers import summaries

        return getattr(summaries, build)()

    def test_names_the_configured_language(self, _set_lang, build) -> None:
        _set_lang("ja")
        assert "Japanese" in self._out(build)
        _set_lang("en")
        assert "English" in self._out(build)

    def test_auto_asks_for_no_particular_language(self, _set_lang, build) -> None:
        _set_lang("auto")
        out = self._out(build)

        assert "Japanese" not in out
        assert "English" not in out

    def test_a_language_outside_the_table_still_reaches_the_model(
        self, _set_lang, build
    ) -> None:
        """The `.get` fallback; the tables hold only ja and en."""
        _set_lang("fr")
        assert " in fr" in self._out(build)


# ---------------------------------------------------------------------------
# Summaries — user prompts
# ---------------------------------------------------------------------------


def _summary_file(**over) -> dict:
    return {"filename": "test.mp4", "title": "", "description": "", **over}


@pytest.mark.parametrize(
    "build",
    ["_build_user_prompt", "_build_detailed_user_prompt"],
)
class TestSummariesUserPrompt:
    """Both user prompts drop the same fields on the same conditions."""

    @staticmethod
    def _out(build: str, indexed: dict, *, was_truncated: bool = False) -> str:
        from app.workers import summaries

        return getattr(summaries, build)(
            indexed, "video", "body text", was_truncated=was_truncated
        )

    def test_omits_title_and_description_when_absent(self, build) -> None:
        out = self._out(build, _summary_file())

        assert "Title:" not in out
        assert "Description:" not in out
        assert "test.mp4" in out
        assert "body text" in out

    def test_carries_title_and_description_when_present(self, build) -> None:
        out = self._out(
            build, _summary_file(title="A title", description="A description")
        )

        assert "Title: A title" in out
        assert "Description: A description" in out

    def test_omits_a_title_that_only_repeats_the_filename(self, build) -> None:
        out = self._out(build, _summary_file(title="test.mp4"))

        assert "Title:" not in out

    def test_marks_a_truncated_body_and_says_nothing_otherwise(
        self, build
    ) -> None:
        whole = self._out(build, _summary_file())
        excerpt = self._out(build, _summary_file(), was_truncated=True)

        assert "excerpt" not in whole
        assert "excerpt" in excerpt


# ---------------------------------------------------------------------------
# Auto tags
# ---------------------------------------------------------------------------


class TestAutoTagsSystemPrompt:
    def test_builds_from_the_auto_tags_template(self, _set_lang) -> None:
        """The builder names its template; nothing else pins that string."""
        from app.workers import auto_tags

        _set_lang("auto")
        assert "tagging assistant" in auto_tags._build_system_prompt()

    def test_names_the_configured_language(self, _set_lang) -> None:
        from app.workers import auto_tags

        _set_lang("ja")
        assert "Japanese" in auto_tags._build_system_prompt()
        _set_lang("en")
        assert "English" in auto_tags._build_system_prompt()

    def test_auto_asks_for_no_particular_language(self, _set_lang) -> None:
        from app.workers import auto_tags

        _set_lang("auto")
        out = auto_tags._build_system_prompt()

        assert "Output tags in" not in out
        assert "Japanese" not in out
        assert "English" not in out

    def test_a_language_outside_the_table_still_reaches_the_model(
        self, _set_lang
    ) -> None:
        """The `.get` fallback; the table holds only ja and en."""
        from app.workers import auto_tags

        _set_lang("fr")
        assert "Output tags in fr" in auto_tags._build_system_prompt()


class TestAutoTagsUserPrompt:
    @staticmethod
    def _file(**over) -> dict:
        return {
            "filename": "f.mp4",
            "title": "",
            "description": "",
            "tags_text": "",
            **over,
        }

    def _out(self, indexed=None, existing=None, candidates=None) -> str:
        from app.workers import auto_tags

        return auto_tags._build_user_prompt(
            indexed if indexed is not None else self._file(),
            "video",
            "body text",
            existing if existing is not None else [],
            candidates,
        )

    def test_omits_a_title_that_only_repeats_the_filename(self) -> None:
        assert "f.mp4" not in self._out(self._file(title="f.mp4")).replace(
            "Filename: f.mp4", ""
        )

    def test_carries_a_title_that_differs_from_the_filename(self) -> None:
        assert "Another title" in self._out(self._file(title="Another title"))

    def test_says_none_when_the_file_has_no_tags_yet(self) -> None:
        assert "none" in self._out(existing=[])
        out = self._out(existing=["existing1", "existing2"])
        assert "existing1, existing2" in out

    def test_adds_no_candidate_section_without_candidates(self) -> None:
        from app.workers import auto_tags

        assert "Reference candidates" not in self._out()
        empty = auto_tags.TagCandidates(clip=[], tfidf=[], knn=[])
        assert "Reference candidates" not in self._out(candidates=empty)

    def test_lists_each_candidate_source_that_has_entries(self) -> None:
        from app.workers import auto_tags

        out = self._out(
            candidates=auto_tags.TagCandidates(
                clip=["clip1"], tfidf=["tfidf1"], knn=["knn1"]
            )
        )

        assert "Reference candidates" in out
        assert "Tags from similar files: knn1" in out
        assert "Image analysis candidates: clip1" in out
        assert "Keyword extraction candidates: tfidf1" in out
        # k-NN leads: "similar tagged files" is the strongest signal.
        assert out.index("knn1") < out.index("clip1") < out.index("tfidf1")

    def test_omits_a_candidate_source_that_is_empty(self) -> None:
        from app.workers import auto_tags

        out = self._out(
            candidates=auto_tags.TagCandidates(clip=[], tfidf=["tfidf1"], knn=[])
        )

        assert "Reference candidates" in out
        assert "Keyword extraction candidates: tfidf1" in out
        assert "Tags from similar files" not in out
        assert "Image analysis candidates" not in out


# ---------------------------------------------------------------------------
# Refine
# ---------------------------------------------------------------------------


class TestRefinePrompts:
    def test_system_prompt_asks_for_the_configured_script(self, _set_lang) -> None:
        from app.workers import refine

        _set_lang("ja")
        assert "。" in refine._build_system_prompt()
        _set_lang("en")
        out = refine._build_system_prompt()
        assert "periods, commas" in out
        assert "。" not in out

    def test_an_unlisted_language_falls_back_rather_than_naming_one(
        self, _set_lang
    ) -> None:
        from app.workers import refine

        _set_lang("fr")
        out = refine._build_system_prompt()

        assert out == refine.render(
            "refine/system.jinja2",
            punctuation_instruction=refine._DEFAULT_PUNCTUATION,
        )

    def test_user_prompt_is_json_carrying_every_chunk(self) -> None:
        from app.workers import refine

        class _Chunk:
            def __init__(self, cid: int, text: str | None) -> None:
                self.id = cid
                self.text = text

        out = refine._build_user_prompt(
            [_Chunk(1, "hello"), _Chunk(2, "world"), _Chunk(3, None)]
        )
        payload = json.loads(out[out.index("[") : out.rindex("]") + 1])

        assert payload == [
            {"id": 1, "text": "hello"},
            {"id": 2, "text": "world"},
            # A chunk with no text stays in the window: dropping it would
            # desync the id set `_parse_llm_response` checks against.
            {"id": 3, "text": ""},
        ]


# ---------------------------------------------------------------------------
# Vision
# ---------------------------------------------------------------------------


class TestVisionSystemPrompt:
    @pytest.mark.parametrize("lang", ["auto", "", "not a tag"])
    def test_falls_back_to_inference_for_auto_blank_and_invalid(
        self, lang
    ) -> None:
        from app import llm

        out = llm._build_vision_system_prompt(lang)

        assert "same language as the filename" in out
        assert "IETF BCP 47" not in out


# ---------------------------------------------------------------------------
# RAG
# ---------------------------------------------------------------------------


class TestRagAnswerPrompt:
    def test_system_prompt_names_the_configured_language(self) -> None:
        from app.rag import prompt as rag_prompt

        assert "Japanese" in rag_prompt.build_system_prompt("ja")
        assert "English" in rag_prompt.build_system_prompt("en")

    def test_system_prompt_names_none_on_auto(self) -> None:
        from app.rag import prompt as rag_prompt

        out = rag_prompt.build_system_prompt("auto")

        assert "Japanese" not in out
        assert "English" not in out

    def test_a_language_outside_the_table_still_reaches_the_model(self) -> None:
        """The `.get` fallback; the table holds only ja and en."""
        from app.rag import prompt as rag_prompt

        assert "Answer in fr" in rag_prompt.build_system_prompt("fr")

    def test_user_prompt_is_well_formed_without_context(self) -> None:
        from app.rag import prompt as rag_prompt

        out = rag_prompt.build_user_prompt("the query", [])

        assert "the query" in out
        assert "file_id" not in out

    def test_user_prompt_carries_each_file_and_its_snippets(self) -> None:
        from app.rag import prompt as rag_prompt
        from app.rag.context import ContextSnippet, FileContext

        ctx = FileContext(
            file_id="abc123",
            filename="video.mp4",
            drive="movies",
            file_type="video",
            title="title",
            description="description",
            snippets=(
                ContextSnippet(
                    source="transcript", location="0:45", text="snippet text"
                ),
                ContextSnippet(source="metadata", location=None, text="meta snippet"),
            ),
            total_chars=42,
        )

        out = rag_prompt.build_user_prompt("the query", [ctx])

        assert "abc123" in out
        assert "video.mp4" in out
        assert "snippet text" in out
        assert "0:45" in out
        # A snippet without a location still reaches the model.
        assert "meta snippet" in out


class TestRagModuleLevelSystemPrompts:
    """Each is `render("<name>")` and nothing else, so the name is the whole
    decision — and the two templates are interchangeable without it."""

    def test_decomposer_asks_for_the_fields_its_caller_parses(self) -> None:
        from app.rag import query_decomposer

        out = query_decomposer._SYSTEM_PROMPT

        assert "time_range" in out
        assert "personal_scope" in out
        assert "file_type_hint" in out

    def test_transform_asks_for_required_and_semantic_terms(self) -> None:
        from app.rag import query_transform

        out = query_transform._SYSTEM_PROMPT

        assert "required" in out
        assert "semantic" in out
        assert "time_range" not in out


class TestRagParameterisedSystemPrompts:
    def test_clue_generator_asks_for_the_count_it_was_given(self) -> None:
        assert "4" in render("rag/clue_generator_system.jinja2", clue_count=4)
        assert "9" in render("rag/clue_generator_system.jinja2", clue_count=9)

    def test_category_expander_asks_for_the_cap_it_was_given(self) -> None:
        assert "5" in render("rag/category_expander_system.jinja2", max_terms=5)
        assert "12" in render("rag/category_expander_system.jinja2", max_terms=12)
